---
title: "Project overview"
format: html
editor: visual
---

# Project Overview

## Project Aim

Finding trends in data from Uniprot

We will focus on differences between mouse and human and use logo plots for active sequences

Be aware that all data-analysis result is dependent on what have been reported in uniprot, and do not necessarily reflect real life.

## Analysis tracks

### Bar plots

-   Examine columns like "pathway" in bar plots. Do ratio on y-axis and not just counts, to adjust for what is most studied

-   

### Sequence Logo Plots

-   Compare differences between similar protein families

-   Compare differences between Mouse and Human for same protein families

-   Look at EC numbers

-   Transmembrane domains

## Line
See if there is something interesting about pH dependence. Finding: There are only 100 mouse entries with pH dependence data. This greatly limits the analysis. Overall the pH dependence is slightly lower for mice (mean~7) compared to human (mean~7.5) but it is not very explicit. There is no obvious trend in pH vs subcellular location for the top 5 subcellular locations. There is a little difference between pH vs enzyme class, however, there are not enough datapoints for mice to compare between organisms.

## Anton

## Jeppe

Bar plots of top 10 pathways counted in mouse vs human

## Johan

## Oscar
