---
title: "line"
format: html
editor: visual
---

## test

```{r}
library(tidyverse)
```

```{r}
function_data <- read_tsv(file = "../data/_raw/function_file.tsv.gz")
```

```{r}
#We remove 60 rows with information about pH dependence with this method because we are strich in our str_extract.

#Function for extracting the optimum pH from the pH dependence column
pH_str_search <- "Optimum pH is (\\d+\\.\\d*)-(\\d+\\.\\d*)|Optimum pH is (\\d+\\.\\d*)|Optimum pH is around (\\d+\\.\\d*)|Optimum pH is about (\\d+\\.\\d*)|Optimum pH is (\\d+\\.\\d*) to (\\d+\\.\\d*)|Optimum pH is between (\\d+\\.\\d*) and (\\d+\\.\\d*)"

#Function for creating two new columns for pH interval values
pH_columns <- str_c("pH_", seq(from = 1, to = 2))


pH_clean_data <- function_data |>
  #Removes text and keeps optimum pH values
  mutate(`pH dependence` = str_extract(`pH dependence`, pH_str_search),
         `pH dependence` = str_remove(`pH dependence`, "Optimum pH is"),
         `pH dependence` = str_remove(`pH dependence`, "about|around|between"),
         `pH dependence` = str_replace(`pH dependence`, " and ", "-")) |>
  #Creates a new variable with pH interval
  mutate(pH_interval = str_extract(`pH dependence`, "(\\d+\\.\\d*)-(\\d+\\.\\d*)")) |>
  #Separates pH interval into columns
  separate(pH_interval, into = pH_columns, sep = "-") |>
  #Inserts optimum pH values from pH dependence if it is not and interval
  mutate(pH_1 = coalesce(pH_1, `pH dependence`),
         pH_2 = coalesce(pH_2, `pH dependence`)) |>
  #Changes chr to dbl and calculates average pH optimum
  mutate(pH_1 = as.numeric(pH_1),
         pH_2 = as.numeric(pH_2),
         `pH dependence` = (pH_1+pH_2)/2) |>
  select(-pH_1,-pH_2)
pH_clean_data
```
