---
title: "Data Cleaning"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r, echo=FALSE, message=FALSE}


data <- read_tsv("~/group_20_project/data/clean_data.tsv")


```

### Descrptive statistics

## Organism types 

```{r}

data %>% group_by(organism) %>%  summarise(Amount = n()) %>% 
  ggplot(aes(x=organism, y = Amount, fill = organism)) +
    geom_bar(stat = "identity") + coord_flip() +
    theme_classic() +
    theme(legend.position = "none") +
    labs(title = "Types of organisms in the dataset")

```

```{r}
data %>% 
  select(cofactor, `subcellular_location_[cc]`, GO_molecular_function, protein_family, enzyme_class, pathway) %>% 
  filter(!is.na(cofactor),
         !is.na(`subcellular_location_[cc]`),
         !is.na(GO_molecular_function),
         !is.na(protein_family),
         !is.na(enzyme_class),
         !is.na(pathway)) %>%
  pivot_longer(cols = c(cofactor, `subcellular_location_[cc]`, GO_molecular_function, protein_family, enzyme_class, pathway),
               names_to = "Column", values_to = "Value") %>%
  group_by(Column) %>%
  summarise(Unique_Entries = n_distinct(Value))
```


```{r}

library(dplyr)
library(tidyr)

data %>% 
  select(cofactor, `subcellular_location_[cc]`, GO_molecular_function, protein_family, enzyme_class, pathway) %>% 
  filter(!is.na(cofactor),
         !is.na(`subcellular_location_[cc]`),
         !is.na(GO_molecular_function),
         !is.na(protein_family),
         !is.na(enzyme_class),
         !is.na(pathway)) %>%
  pivot_longer(cols = c(cofactor, `subcellular_location_[cc]`, GO_molecular_function, protein_family, enzyme_class, pathway),
               names_to = "Column", values_to = "Value") %>%
  group_by(Column) %>%
  summarise(Unique_Entries = n_distinct(Value)) %>% 
  ggplot(aes(x=Column, y=Unique_Entries, fill = Column)) +
    geom_bar(stat = "identity") +
    coord_flip()






```

```{r}


data %>% select(enzyme_class) %>% 
  group_by(enzyme_class) %>% 
  summarise(Amount = n()) %>% 
  ggplot(aes(x=enzyme_class, y=Amount, fill=enzyme_class)) +
    geom_bar(stat = "identity") +
    coord_flip()
  
  



```



